(() => {
'use strict';
const STORE='fs_gestao_resultados_v2';
const ENDPOINT='https://script.google.com/macros/s/AKfycbx9pLFWtpngXQemQLORPiY16pGlxKTU7Hw10cSZSzieoiMmn-CStDKfo5oUENimSwzv/exec';
const TOKEN='2c97791424feb4029ae889e3ab094596b158d2f4c680172b';
const brl=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}); const pct=new Intl.NumberFormat('pt-BR',{style:'percent',minimumFractionDigits:2,maximumFractionDigits:2});
const now=new Date(), month=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`;
const name=String(localStorage.getItem('fs_nome')||'VENDEDOR').trim(); const branchText=String(localStorage.getItem('fs_filial')||'').trim();
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toUpperCase().replace(/\s+/g,' '); const digits=v=>String(v||'').replace(/\D/g,'');
const branchMatch=(a,b)=>{const da=digits(a),db=digits(b);return da&&db?Number(da)===Number(db):norm(a)===norm(b)};
const num=v=>{if(typeof v==='number')return Number.isFinite(v)?Math.max(0,v):0;let s=String(v??'').replace(/R\$|\s/g,'');if(s.includes(','))s=s.replace(/\./g,'').replace(',','.');const n=Number(s);return Number.isFinite(n)?Math.max(0,n):0};
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const sellerId=s=>s?.id||`seller-${norm(s?.name).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'vendedor'}`;
const emptyDay=key=>({status:new Date(`${key}T12:00:00`).getDay()===0?'off':'pending',general:0,eligible:0,invoiceCount:0,nfs:0,warranty:0,warrantyQty:0,other:0,mixed:0,updatedAt:new Date(0).toISOString()});
let vault=null, record=null, seller=null, dirty=false, saving=false;
const state=(t,tone='ok')=>{const e=document.getElementById('syncState');e.textContent=t;e.style.background=tone==='err'?'#fff0f2':tone==='busy'?'#fff6e4':'#e9f8f1';e.style.color=tone==='err'?'#b42335':tone==='busy'?'#8a5b05':'#087a4b'};
function localVault(){try{return JSON.parse(localStorage.getItem(STORE)||'null')}catch{return null}}
function recordKey(r){return `${String(r.branch||'SEM FILIAL').trim().toUpperCase()}|${r.month}`}
function findRecord(v,m=month){const rows=Object.values(v?.records||{}).filter(r=>branchMatch(r.branch,branchText));return rows.find(r=>r.month===m)||rows.sort((a,b)=>String(b.month).localeCompare(String(a.month)))[0]||null}
function ensureSeller(r){r.sellers=Array.isArray(r.sellers)?r.sellers:[];let s=r.sellers.find(x=>norm(x.name)===norm(name));if(!s){s={id:sellerId({name}),name,daily:{},assignedGoal:0,serviceGoal:0,commissionMercantileRate:0,commissionServiceRate:5,updatedAt:new Date().toISOString()};r.sellers.push(s)}s.daily=s.daily&&typeof s.daily==='object'?s.daily:{};s.id=sellerId(s);return s}
function aggregate(s){const a={general:0,eligible:0,invoiceCount:0,nfs:0,warranty:0,warrantyQty:0,other:0,mixed:0,days:0};Object.values(s?.daily||{}).forEach(d=>{a.general+=num(d.general);a.eligible+=num(d.eligible);a.invoiceCount+=num(d.invoiceCount);a.nfs+=num(d.nfs);a.warranty+=num(d.warranty);a.warrantyQty+=num(d.warrantyQty);a.other+=num(d.other);a.mixed+=num(d.mixed);if(d.status==='done')a.days++});a.services=a.warranty+a.other+a.mixed;a.efficiency=a.eligible?a.services/a.eligible:0;a.conversion=a.nfs?a.warrantyQty/a.nfs:0;a.ticket=a.invoiceCount?a.general/a.invoiceCount:0;return a}
function syncLegacy(s){const a=aggregate(s);['general','eligible','invoiceCount','nfs','warranty','warrantyQty','other','mixed','days'].forEach(k=>s[k]=a[k]);return a}
function jsonpLoad(){return new Promise((resolve,reject)=>{const cb=`__sellerCloud_${Date.now()}`;const sc=document.createElement('script');const done=()=>{delete window[cb];sc.remove()};window[cb]=res=>{done();res?.ok?resolve(res.vault):reject(new Error(res?.error||'Falha'))};sc.onerror=()=>{done();reject(new Error('Conexão'))};sc.src=`${ENDPOINT}?action=load&token=${encodeURIComponent(TOKEN)}&callback=${cb}&_=${Date.now()}`;document.head.appendChild(sc)})}
async function postVault(v){await fetch(ENDPOINT,{method:'POST',mode:'no-cors',cache:'no-store',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'save',token:TOKEN,vault:v})})}
function mergeSeller(remoteSeller,localSeller){const out={...(remoteSeller||{}),...(localSeller||{})};const rd=remoteSeller?.daily||{},ld=localSeller?.daily||{};out.daily={...rd};for(const [k,d] of Object.entries(ld)){const r=rd[k];out.daily[k]=!r||Date.parse(d.updatedAt||0)>=Date.parse(r.updatedAt||0)?d:r}return out}
async function saveCloud(message='Dados enviados para a gestão'){if(saving)return;saving=true;state('↑ Sincronizando com a nuvem…','busy');try{syncLegacy(seller);seller.updatedAt=new Date().toISOString();record.updatedAt=new Date().toISOString();let remote=await jsonpLoad().catch(()=>null);if(!remote)remote=vault||{version:2,currentKey:'',records:{}};remote.records=remote.records||{};let rr=findRecord(remote,record.month);if(!rr){rr=JSON.parse(JSON.stringify(record));remote.records[recordKey(rr)]=rr}else{rr.sellers=Array.isArray(rr.sellers)?rr.sellers:[];const i=rr.sellers.findIndex(x=>norm(x.name)===norm(name));if(i>=0)rr.sellers[i]=mergeSeller(rr.sellers[i],seller);else rr.sellers.push(JSON.parse(JSON.stringify(seller)));rr.updatedAt=new Date().toISOString()}remote.currentKey=recordKey(rr);remote._cloudUpdatedAt=new Date().toISOString();await postVault(remote);vault=remote;record=rr;seller=ensureSeller(record);localStorage.setItem(STORE,JSON.stringify(remote));dirty=false;state(`✓ ${message}`);render()}catch(e){state('⚠ Salvo neste aparelho; tente sincronizar novamente','err');localStorage.setItem(STORE,JSON.stringify(vault))}finally{saving=false}}
async function pull(){if(dirty||saving)return;try{const remote=await jsonpLoad();if(!remote)return;const rr=findRecord(remote,month)||findRecord(remote);if(!rr)return;const rs=(rr.sellers||[]).find(x=>norm(x.name)===norm(name));vault=remote;record=rr;seller=rs||ensureSeller(record);localStorage.setItem(STORE,JSON.stringify(remote));state('✓ Sincronizado com a nuvem');render()}catch{state('⚠ Sem conexão com a nuvem; usando dados deste aparelho','err')}}
function goalPercent(key){return num(record?.daily?.[key]?.goalPercent)}
function sellerCount(){return Math.max(num(record?.sellerCount), (record?.sellers||[]).filter(s=>String(s.name||'').trim()).length,1)}
function dailyMission(key){const p=goalPercent(key),count=sellerCount();return{p,individualMerc:num(seller.assignedGoal)*p/100,individualServices:num(seller.serviceGoal)*p/100,branchMerc:num(record?.mercantileGoal)*p/100/count,branchServices:(num(record?.mercantileGoal)*p/100*.07)/count}}
function allDays(){const [y,m]=record.month.split('-').map(Number),days=new Date(y,m,0).getDate();return Array.from({length:days},(_,i)=>{const key=`${y}-${String(m).padStart(2,'0')}-${String(i+1).padStart(2,'0')}`;return{key,date:new Date(`${key}T12:00:00`),data:seller.daily[key]||emptyDay(key)}})}
function statusClass(rate){return rate>=1?'positive':rate>=.85?'warning':'negative'}
function moneyField(v){return v?brl.format(num(v)):''}
function renderHome(){const a=aggregate(seller),mg=num(seller.assignedGoal),sg=num(seller.serviceGoal),mr=mg?a.general/mg:0,sr=sg?a.services/sg:0;document.getElementById('welcome').textContent=`${name.split(/\s+/)[0]}, acompanhe seu resultado`;document.getElementById('goalProgress').innerHTML=`<div class="goal-card"><div class="goal-row"><div><b>Meta mercantil individual</b><div>${brl.format(a.general)} de ${brl.format(mg)}</div></div><strong class="${statusClass(mr)}">${pct.format(mr)}</strong></div><div class="bar"><i style="width:${Math.min(100,mr*100)}%"></i></div><small>${mr>=1?`Acima da meta em ${brl.format(a.general-mg)}`:`Faltam ${brl.format(Math.max(0,mg-a.general))}`}</small></div><div class="goal-card service"><div class="goal-row"><div><b>Meta de serviços individual</b><div>${brl.format(a.services)} de ${brl.format(sg)}</div></div><strong class="${statusClass(sr)}">${pct.format(sr)}</strong></div><div class="bar"><i style="width:${Math.min(100,sr*100)}%"></i></div><small>${sr>=1?`Acima da meta em ${brl.format(a.services-sg)}`:`Faltam ${brl.format(Math.max(0,sg-a.services))}`}</small></div>`;document.getElementById('homeMetrics').innerHTML=[['Venda mercantil',brl.format(a.general),mg?`${pct.format(mr)} da meta`: 'Cadastre sua meta'],['Serviços',brl.format(a.services),sg?`${pct.format(sr)} da meta`:'Cadastre sua meta'],['Conversão',a.nfs?pct.format(a.conversion):'—','Meta 35,00%'],['Eficiência',a.eligible?pct.format(a.efficiency):'—','Meta 7,00%'],['Ticket médio',brl.format(a.ticket),`${a.invoiceCount} nota(s) fiscal(is)`],['Dias lançados',String(a.days),`${Math.max(0,num(seller.plannedDays||record.businessDays)-a.days)} restante(s)`]].map(x=>`<div class="metric"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('');let msg='Comece cadastrando suas metas e preenchendo os resultados do dia.';if(mg&&a.general>=mg&&sg&&a.services>=sg)msg='🔥 Dupla meta individual batida! Parabéns. Continue contribuindo para ampliar o resultado da filial.';else if(mg&&a.general>=mg)msg='🎯 Meta mercantil individual batida! Agora mantenha o ritmo e ajude a filial a ir além.';else if(sg&&a.services>=sg)msg='✅ Meta de serviços batida! Continue avançando na meta mercantil.';document.getElementById('motivation').textContent=msg}
function renderGoals(){document.getElementById('goalMerc').value=moneyField(seller.assignedGoal);document.getElementById('goalServices').value=moneyField(seller.serviceGoal)}
function renderDaily(){const list=document.getElementById('dayList');list.innerHTML=allDays().map(({key,date,data})=>{const m=dailyMission(key),services=num(data.warranty)+num(data.other)+num(data.mixed),eff=num(data.eligible)?services/num(data.eligible):0,conv=num(data.nfs)?num(data.warrantyQty)/num(data.nfs):0;return `<article class="day" data-key="${key}"><div class="day-head"><div><strong>${date.toLocaleDateString('pt-BR',{day:'2-digit',month:'long'})}</strong><small>${date.toLocaleDateString('pt-BR',{weekday:'long'})}</small></div><select data-f="status"><option value="pending" ${data.status==='pending'?'selected':''}>Pendente</option><option value="done" ${data.status==='done'?'selected':''}>✓ Lançado</option><option value="off" ${data.status==='off'?'selected':''}>Não trabalha</option></select></div><div class="day-body"><div class="mission"><div><span>% DA FILIAL</span><strong>${m.p?`${m.p.toLocaleString('pt-BR')}%`:'—'}</strong></div><div><span>MINHA META DO DIA</span><strong>${m.p?brl.format(m.individualMerc):'—'}</strong></div><div><span>REFERÊNCIA FILIAL</span><strong>${m.p?brl.format(m.branchMerc):'—'}</strong></div><div><span>SERVIÇOS INDIVIDUAL</span><strong>${m.p?brl.format(m.individualServices):'—'}</strong></div></div><div class="daily-grid">${[['general','Venda mercantil'],['eligible','Venda elegível'],['warranty','Garantias (R$)'],['other','Outros serviços'],['mixed','Presta-mista']].map(([f,l])=>`<div class="field"><label>${l}</label><input data-f="${f}" inputmode="decimal" value="${moneyField(data[f])}"></div>`).join('')}${[['invoiceCount','Notas fiscais'],['nfs','Qtd. elegível'],['warrantyQty','Qtd. garantias']].map(([f,l])=>`<div class="field"><label>${l}</label><input data-f="${f}" type="number" min="0" step="1" value="${num(data[f])||''}"></div>`).join('')}</div><div class="day-results"><div><span>SERVIÇOS</span><strong>${brl.format(services)}</strong></div><div><span>CONVERSÃO</span><strong class="${statusClass(conv/.35)}">${num(data.nfs)?pct.format(conv):'—'}</strong></div><div><span>EFICIÊNCIA</span><strong class="${statusClass(eff/.07)}">${num(data.eligible)?pct.format(eff):'—'}</strong></div><div><span>SITUAÇÃO</span><strong>${m.p&&num(data.general)>=m.individualMerc?'Meta do dia ✓':'Em andamento'}</strong></div></div></div></article>`}).join('');list.querySelectorAll('[data-f]').forEach(el=>el.addEventListener('change',async e=>{const box=e.target.closest('[data-key]'),key=box.dataset.key,f=e.target.dataset.f,d={...(seller.daily[key]||emptyDay(key))};if(f==='status'){d.status=e.target.value;if(d.status==='off')['general','eligible','invoiceCount','nfs','warranty','warrantyQty','other','mixed'].forEach(k=>d[k]=0)}else{d[f]=['invoiceCount','nfs','warrantyQty'].includes(f)?Math.round(num(e.target.value)):num(e.target.value);if(d.status==='pending')d.status='done'}d.updatedAt=new Date().toISOString();seller.daily[key]=d;dirty=true;syncLegacy(seller);render();await saveCloud('Resultado atualizado para a gestão')}))}
function weeks(){const days=allDays(),b=[];days.forEach(it=>{const d=new Date(it.date);d.setDate(d.getDate()-((d.getDay()+6)%7));const k=d.toISOString().slice(0,10);let w=b.find(x=>x.k===k);if(!w){w={k,items:[]};b.push(w)}w.items.push(it)});return b}
function sumDays(items){const s={daily:{}};items.forEach(x=>s.daily[x.key]=x.data);return aggregate(s)}
function renderWeekly(){document.getElementById('weekList').innerHTML=weeks().map((w,i)=>{const a=sumDays(w.items),mg=num(seller.assignedGoal)/weeks().length,sg=num(seller.serviceGoal)/weeks().length;return `<article class="week"><div class="week-head"><div><strong>${i+1}ª semana</strong><div class="hint">${w.items[0].date.toLocaleDateString('pt-BR')} a ${w.items.at(-1).date.toLocaleDateString('pt-BR')}</div></div><b class="${statusClass(mg?a.general/mg:0)}">${mg?pct.format(a.general/mg):'—'}</b></div><div class="week-grid">${[['Mercantil',brl.format(a.general),`Meta ref. ${brl.format(mg)}`],['Serviços',brl.format(a.services),`Meta ref. ${brl.format(sg)}`],['Conversão',a.nfs?pct.format(a.conversion):'—','Meta 35%'],['Eficiência',a.eligible?pct.format(a.efficiency):'—','Meta 7%']].map(x=>`<div class="metric"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('')}</div></article>`}).join('')}
function sellerInRecord(r){return (r?.sellers||[]).find(x=>norm(x.name)===norm(name))}
function renderPeriods(){const rows=Object.values(vault?.records||{}).filter(r=>branchMatch(r.branch,branchText)).sort((a,b)=>String(b.month).localeCompare(String(a.month)));const current=sellerInRecord(rows.find(r=>r.month===record.month)||record)||seller;const prevRecord=rows.find(r=>r.month<record.month),prev=sellerInRecord(prevRecord);const card=(title,s,r)=>{if(!s)return `<div class="panel"><h3>${title}</h3><div class="empty">Sem dados.</div></div>`;const a=s.daily?aggregate(s):{general:num(s.general),services:num(s.warranty)+num(s.other)+num(s.mixed),eligible:num(s.eligible),nfs:num(s.nfs),warrantyQty:num(s.warrantyQty)};a.efficiency=a.eligible?a.services/a.eligible:0;a.conversion=a.nfs?a.warrantyQty/a.nfs:0;return `<div class="panel"><h3>${title}</h3><div class="grid"><div class="metric"><span>Mercantil</span><strong>${brl.format(a.general)}</strong></div><div class="metric"><span>Serviços</span><strong>${brl.format(a.services)}</strong></div><div class="metric"><span>Conversão</span><strong>${a.nfs?pct.format(a.conversion):'—'}</strong></div><div class="metric"><span>Eficiência</span><strong>${a.eligible?pct.format(a.efficiency):'—'}</strong></div></div></div>`};document.getElementById('periodCompare').innerHTML=card(`Atual · ${record.month}`,current,record)+card(prevRecord?`Anterior · ${prevRecord.month}`:'Período anterior',prev,prevRecord)}
function render(){if(!record||!seller)return;document.getElementById('who').childNodes[0].nodeValue=name;document.getElementById('where').textContent=`${record.branch||branchText} • ${record.month}`;renderHome();renderGoals();renderDaily();renderWeekly();renderPeriods()}
function parseMoneyInput(el){const n=num(el.value);el.value=n?brl.format(n):'';return n}
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===b.dataset.view));window.scrollTo({top:0,behavior:'smooth'})}));
document.getElementById('saveGoals').addEventListener('click',async()=>{seller.assignedGoal=parseMoneyInput(document.getElementById('goalMerc'));seller.serviceGoal=parseMoneyInput(document.getElementById('goalServices'));seller.updatedAt=new Date().toISOString();dirty=true;await saveCloud('Metas atualizadas para a gestão')});
async function downloadImage(){const a=aggregate(seller),mg=num(seller.assignedGoal),sg=num(seller.serviceGoal),c=document.createElement('canvas');c.width=1080;c.height=1450;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);const grad=x.createLinearGradient(0,0,1080,0);grad.addColorStop(0,'#0879e8');grad.addColorStop(1,'#6049e8');x.fillStyle=grad;x.roundRect(55,55,970,210,34);x.fill();x.fillStyle='#fff';x.font='900 48px Arial';x.fillText('MEU RESULTADO',90,135);x.font='700 25px Arial';x.fillText(`${name} | ${record.branch||branchText} | ${record.month}`,90,190);const metric=(xx,yy,label,value,note)=>{x.fillStyle='#f4f7fb';x.roundRect(xx,yy,445,150,24);x.fill();x.fillStyle='#66788f';x.font='800 18px Arial';x.fillText(label,xx+24,yy+38);x.fillStyle='#102a43';x.font='900 34px Arial';x.fillText(value,xx+24,yy+84);x.fillStyle='#66788f';x.font='600 17px Arial';x.fillText(note,xx+24,yy+120)};metric(55,315,'VENDA MERCANTIL',brl.format(a.general),mg?`${pct.format(a.general/mg)} da meta`:'Meta não cadastrada');metric(580,315,'SERVIÇOS',brl.format(a.services),sg?`${pct.format(a.services/sg)} da meta`:'Meta não cadastrada');metric(55,490,'CONVERSÃO',a.nfs?pct.format(a.conversion):'—','Meta 35,00%');metric(580,490,'EFICIÊNCIA',a.eligible?pct.format(a.efficiency):'—','Meta 7,00%');metric(55,665,'META MERCANTIL',brl.format(mg),a.general>=mg&&mg?'META BATIDA ✓':`Faltam ${brl.format(Math.max(0,mg-a.general))}`);metric(580,665,'META SERVIÇOS',brl.format(sg),a.services>=sg&&sg?'META BATIDA ✓':`Faltam ${brl.format(Math.max(0,sg-a.services))}`);x.fillStyle='#edf7ff';x.roundRect(55,875,970,260,28);x.fill();x.fillStyle='#0879e8';x.font='900 30px Arial';x.fillText('RESULTADO ATUALIZADO',90,930);x.fillStyle='#102a43';x.font='700 25px Arial';const msg=mg&&a.general>=mg?'Parabéns! Meta mercantil individual atingida. Seguimos contribuindo para a filial.':'Seguimos em busca da meta. Cada atendimento pode fazer a diferença.';const words=msg.split(' ');let line='',yy=985;for(const w of words){const t=line+w+' ';if(x.measureText(t).width>860){x.fillText(line,90,yy);line=w+' ';yy+=38}else line=t}x.fillText(line,90,yy);x.fillStyle='#748296';x.font='600 18px Arial';x.fillText(`Gerado em ${new Date().toLocaleString('pt-BR')} pela Gestão de Resultados`,55,1340);const blob=await new Promise(r=>c.toBlob(r,'image/png'));const url=URL.createObjectURL(blob),ael=document.createElement('a');ael.href=url;ael.download=`meu-resultado-${norm(name).toLowerCase().replace(/[^a-z0-9]+/g,'-')}-${record.month}.png`;ael.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
document.getElementById('downloadImage').addEventListener('click',downloadImage);
(async function init(){document.getElementById('who').childNodes[0].nodeValue=name;document.getElementById('where').textContent=branchText;vault=localVault()||{version:2,currentKey:'',records:{}};record=findRecord(vault,month)||findRecord(vault);if(record)seller=ensureSeller(record);if(record&&seller){render();state('⟳ Conferindo a nuvem…','busy')}await pull();if(!record){state('⚠ Nenhuma competência da filial encontrada. Peça ao gestor para abrir/configurar o mês primeiro.','err');document.getElementById('homeMetrics').innerHTML='<div class="empty">Aguardando a competência da filial ser criada pelo gestor.</div>';return}if(!seller){seller=ensureSeller(record);dirty=true;await saveCloud('Seu acesso foi vinculado à equipe')}setInterval(pull,12000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)pull()})})();
})();
